### PR TITLE
Toast

### PR DESCRIPTION
**Pull request by manish-GH**
Added Toast component and the landing page
Toast: https://cyber-ui.netlify.app/components/toast/
Landing Page: https://cyber-ui.netlify.app/

### CODE REVIEW

**Review by Sahil25061999 — APPROVED** [review]
looks good just add padding to navbar

**Comment by manish-GH** [comment]
> looks good just add padding to navbar

Hmm, actually I have added the padding, because of the scroll-bar it might seem like the padding is missing. I'm assuming you are referring to the right end of the navbar. At this point I'm not sure how to fix that

**Review by sri-rishi — APPROVED** [review]
Couldn't find any major changes,  looks good to merge

**Review by pradipgharge — COMMENTED** [review]
The home page link on the docs page ain't working, the rest looks good to merge.

**Pull request merged**
